steps:
# Step 1: Build the Docker Image
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'asia-south1-docker.pkg.dev/protailors/cloud-run-source-deploy/protailer:prod', '.' ]

# Step 2: Push the image to the Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'asia-south1-docker.pkg.dev/protailors/cloud-run-source-deploy/protailer:prod' ]


# Step 3: Deployment to Cloud Run after image is pushed
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'protailer'  # Replace with your service name
  - '--image'
  - 'asia-south1-docker.pkg.dev/protailors/cloud-run-source-deploy/protailer:prod'
  - '--region'
  - 'asia-south1'  # You can change this if you want to deploy to a different region
  - '--platform'
  - 'managed'
  # Optional: if you want to allow unauthenticated access
  - '--allow-unauthenticated'
  # Add logging options to build
options:
  logging: CLOUD_LOGGING_ONLY
